{
  parserClass="solutions.sulfura.projectionsdslintellijplugin.psi.ProjectionsDslParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ProjectionsDsl"
  psiImplClassSuffix="Impl"
  psiPackage="solutions.sulfura.projectionsdslintellijplugin.psi"
  psiImplPackage="solutions.sulfura.projectionsdslintellijplugin.psi.impl"

  elementTypeHolderClass="solutions.sulfura.projectionsdslintellijplugin.psi.SimpleTypes"
  elementTypeClass="solutions.sulfura.projectionsdslintellijplugin.psi.ProjectionsDslElementType"
  tokenTypeClass="solutions.sulfura.projectionsdslintellijplugin.psi.ProjectionsDslTokenType"

  psiImplUtilClass="solutions.sulfura.projectionsdslintellijplugin.psi.ProjectionsDslPsiUtil"
}


projectionRoot ::= SPACE* projection SPACE*

projection ::= PROJECTION_START SPACE* projectionContent SPACE* (SEPARATOR SPACE*)? PROJECTION_END

projectionContent ::= propertyName ( SPACE* (SEPARATOR|projection) SPACE* propertyName)* SPACE* (SEPARATOR? SPACE* projection)?

propertyName ::= FIELD_NAME
{
    methods=[getReferences]
}